#!/bin/bash

DIR="your_directory"  # Replace with the path to your directory

# Initialize previous directory size
PREVIOUS_SIZE=0

while true; do
    # Get the current total size of the directory (in bytes)
    CURRENT_SIZE=$(du -sb "$DIR" | awk '{ print $1 }')

    # Check if the directory size has changed
    if [[ "$CURRENT_SIZE" != "$PREVIOUS_SIZE" ]]; then
        echo -e "Checking size of MinION sequencing directory"
        echo -e "Current size: ${CURRENT_SIZE} || Previous size: ${PREVIOUS_SIZE}"
        echo -e "Directory size has changed. Repeating workflow"
        PREVIOUS_SIZE=$CURRENT_SIZE

        rm -rf ${WD}/work; rm -rf 

        nextflow 

    else
        echo -e "Directory size remains the same. Exiting loop."
        break
    fi

    # Wait before checking again
    sleep 2  # Wait 2 seconds before repeating the loop
done
